/**
 * Transcript Panel Controller.
 * Manages incremental rendering, timestamps, auto-scroll, and export utilities.
 */

class TranscriptController {
  constructor() {
    this.container = null;
    this.autoScroll = true;
  }

  init() {
    this.container = document.getElementById('transcript-container');
  }

  renderSegments(segments) {
    if (!this.container) return;

    if (!segments || segments.length === 0) {
      this.container.innerHTML = `
        <div class="empty-state">
          <div class="empty-icon">🎙</div>
          <p class="empty-title">Ready for Consultation Audio</p>
          <p class="empty-subtitle">Click "Start Mic" and begin speaking. Real-time transcription will stream here locally on CPU.</p>
        </div>
      `;
      return;
    }

    // Build segments HTML
    const html = segments.map((seg) => `
      <div class="transcript-segment" data-id="${seg.id}">
        <div class="segment-meta">
          <span class="segment-badge">Segment #${seg.id}</span>
          <span class="segment-time">${seg.timestamp || ''}</span>
          <span class="segment-stats">${seg.duration ? seg.duration + 's audio' : ''} ${seg.inference_time ? '· ' + seg.inference_time + 's latency' : ''}</span>
        </div>
        <div class="segment-text">${this.escapeHtml(seg.text)}</div>
      </div>
    `).join('');

    this.container.innerHTML = html;

    if (this.autoScroll) {
      this.container.scrollTop = this.container.scrollHeight;
    }
  }

  escapeHtml(str) {
    if (!str) return '';
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
  }

  copyToClipboard() {
    const fullText = window.appState.getState().transcript;
    if (!fullText) {
      alert('Transcript is currently empty.');
      return;
    }

    navigator.clipboard.writeText(fullText).then(() => {
      alert('Transcript copied to clipboard!');
    }).catch(() => {
      // Fallback
      const textarea = document.createElement('textarea');
      textarea.value = fullText;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      alert('Transcript copied to clipboard!');
    });
  }

  downloadTranscript() {
    const state = window.appState.getState();
    const fullText = state.transcript;
    if (!fullText) {
      alert('No transcript available to save.');
      return;
    }

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const content = `MEDICAL CONSULTATION TRANSCRIPTION (LOCAL CPU)
Date: ${new Date().toLocaleString()}
Word Count: ${state.wordCount}
Segments: ${state.segmentCount}
=====================================================

${fullText}

=====================================================
Generated by Offline Local CPU Medical Pipeline
Silero VAD + Faster-Whisper`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `medical-transcript-${timestamp}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
}

window.transcriptController = new TranscriptController();
